name: Dry Build
on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - name: Cache yarn
        uses: actions/cache@v1
        with:
          key: 13.x-${{ github.ref }}-yarn
          path: .yarn/cache
          restore-keys: |
            13.x-refs/heads/master-yarn
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          key: 13.x-${{ github.ref }}-node_modules
          path: node_modules
          restore-keys: |
            13.x-refs/heads/master-node_modules
      - uses: actions/setup-node@v1
        with:
          node-version: 13.x
          registry-url: https://npm.pkg.github.com/alorel
      - run: npm install -g yarn@^2.0.0-rc.27
      - run: yarn install --immutable
        env:
          YARN_ENABLE_GLOBAL_CACHE: 'false'
          YARN_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: nelonoel/branch-name@v1
      - name: Dry release
        run: yarn run release --dry-run --branches ${BRANCH_NAME}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
