name: Master Build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - name: Cache yarn
        uses: actions/cache@v1
        with:
          key: 13.x-refs/heads/master-yarn
          path: .yarn/cache
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          key: 13.x-refs/heads/master-node_modules
          path: node_modules
      - uses: actions/setup-node@v1
        with:
          node-version: 13.x
          registry-url: https://npm.pkg.github.com/alorel
      - run: npm install -g yarn@^2.0.0-rc.27
      - run: yarn install --immutable
        env:
          YARN_ENABLE_GLOBAL_CACHE: 'false'
          YARN_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        run: yarn run release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
